const ATS_KEYWORDS = {
  technology: [
    "programming",
    "software",
    "agile",
    "cloud",
    "AI",
    "machine learning",
    "data science",
    "cybersecurity",
    "blockchain",
    "DevOps",
    "frontend",
    "backend",
  ],
  finance: [
    "financial analysis",
    "reporting",
    "compliance",
    "risk management",
    "investment",
    "auditing",
    "budgeting",
    "CFA",
    "taxation",
    "banking",
  ],
  marketing: [
    "campaign management",
    "analytics",
    "social media",
    "SEO",
    "PPC",
    "brand management",
    "email marketing",
    "advertising",
  ],
  healthcare: [
    "patient care",
    "diagnosis",
    "medical coding",
    "EHR",
    "nursing",
    "clinical trials",
    "telemedicine",
    "HIPAA compliance",
  ],
  engineering: [
    "CAD",
    "mechanical design",
    "electrical circuits",
    "robotics",
    "quality assurance",
    "structural analysis",
    "thermodynamics",
  ],
  education: [
    "curriculum design",
    "teaching",
    "e-learning",
    "assessment",
    "classroom management",
    "pedagogy",
    "online learning",
  ],
  human_resources: [
    "recruitment",
    "onboarding",
    "HR policies",
    "performance management",
    "payroll",
    "training and development",
  ],
  legal: [
    "contract law",
    "litigation",
    "intellectual property",
    "corporate law",
    "regulatory affairs",
    "employment law",
    "risk assessment",
  ],
  sales: [
    "lead generation",
    "cold calling",
    "B2B sales",
    "sales funnel",
    "negotiation",
    "CRM",
    "customer acquisition",
  ],
  supply_chain: [
    "logistics",
    "inventory management",
    "procurement",
    "vendor management",
    "warehouse management",
    "distribution",
  ],
  customer_service: [
    "customer support",
    "helpdesk",
    "CRM",
    "issue resolution",
    "client retention",
    "technical support",
  ],
  real_estate: [
    "property management",
    "real estate sales",
    "mortgages",
    "market analysis",
    "leasing",
    "land development",
  ],
  hospitality: [
    "event planning",
    "guest services",
    "hotel management",
    "food and beverage",
    "tourism",
    "restaurant operations",
  ],
  construction: [
    "project management",
    "contractor management",
    "building codes",
    "safety regulations",
    "cost estimation",
    "materials procurement",
  ],
  manufacturing: [
    "lean manufacturing",
    "Six Sigma",
    "quality control",
    "production planning",
    "automation",
    "ISO standards",
  ],
  retail: [
    "inventory management",
    "customer service",
    "merchandising",
    "sales forecasting",
    "retail analytics",
    "pricing strategies",
  ],
  transportation: [
    "fleet management",
    "route optimization",
    "safety compliance",
    "shipping",
    "public transportation",
    "traffic management",
  ],
  energy: [
    "renewable energy",
    "oil and gas",
    "power generation",
    "sustainability",
    "grid management",
    "carbon footprint reduction",
  ],
  government: [
    "policy analysis",
    "public administration",
    "regulatory compliance",
    "legislation",
    "law enforcement",
    "urban planning",
  ],
};

module.exports = ATS_KEYWORDS;
